### ISSUE TITLE
[RFC]: List of endorsed UI libraries, where to go for accordion, modal etc.

### ISSUE THREAD

**Issue by karltaylor** [studio-206/development-guidelines#4]
Great stuff selecting this as the first topic to build out on the developer guidelines.

I think we can all agree that [radiux-ui](https://www.radix-ui.com/) is a tremendously good resource for building our accessible UI's.

- What else can we think of that helps us as long the way with this kind stuff? Can you think of any that you might want to avoid? Why?
- Are we _only_ going to discuss specifically UI Libraries? (Thinking that we don't actually use that many?)
- Could we include specific React lib's that help us? e.g `react-table`, `react-video`, `react-select` for example?

**Comment by pvalentim** [comment]
Some other no-ui component libraries:
https://headlessui.com/
https://ariakit.org/
https://react-spectrum.adobe.com/react-aria/
